# NodeOverlay to add GPU slice extended resources
#
# IMPORTANT: This overlay only affects Karpenter's scheduling simulation.
# It does NOT configure actual GPU slicing on the nodes.
#
# You are responsible for:
# 1. Configuring GPU sharing on your nodes (time-slicing, MIG, MPS, etc.)
# 2. Ensuring your applications are aware they're sharing GPU resources
# 3. Setting appropriate resource limits in your workloads
#
# Common GPU sharing options:
# - NVIDIA Time-Slicing: Software-based sharing, works on all NVIDIA GPUs
# - MIG (Multi-Instance GPU): Hardware partitioning, requires A100/H100
# - MPS (Multi-Process Service): CUDA-level sharing for concurrent kernels
#
# This overlay tells Karpenter that each GPU can serve 4 workloads,
# enabling better bin-packing and consolidation decisions.
---
# Overlay for instances with 1 GPU (g5.xlarge, g5.2xlarge, g4dn.xlarge, etc.)
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: gpu-slices-1gpu
spec:
  weight: 10
  requirements:
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: In
      values: ["1"]
    - key: karpenter.k8s.aws/instance-gpu-manufacturer
      operator: In
      values: ["nvidia"]
  capacity:
    nvidia.com/gpu-slice: 4
---
# Overlay for instances with 2 GPUs
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: gpu-slices-2gpu
spec:
  weight: 10
  requirements:
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: In
      values: ["2"]
    - key: karpenter.k8s.aws/instance-gpu-manufacturer
      operator: In
      values: ["nvidia"]
  capacity:
    nvidia.com/gpu-slice: 8
---
# Overlay for instances with 4 GPUs (g5.12xlarge, p4d.24xlarge, etc.)
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: gpu-slices-4gpu
spec:
  weight: 10
  requirements:
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: In
      values: ["4"]
    - key: karpenter.k8s.aws/instance-gpu-manufacturer
      operator: In
      values: ["nvidia"]
  capacity:
    nvidia.com/gpu-slice: 16
---
# Overlay for instances with 8 GPUs (p4d.24xlarge, p5.48xlarge, etc.)
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: gpu-slices-8gpu
spec:
  weight: 10
  requirements:
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: In
      values: ["8"]
    - key: karpenter.k8s.aws/instance-gpu-manufacturer
      operator: In
      values: ["nvidia"]
  capacity:
    nvidia.com/gpu-slice: 32
